on: [workflow_dispatch]

jobs:
  ziploy_job:
    runs-on: ubuntu-latest
    name: A job to Ziploy
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ziploy your code to server
        id: Ziploy
        uses: code-soup/ziploy-github-action@master