name: Deploy with Ziploy

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: false

jobs:
  my_job:
    runs-on: ubuntu-latest
    name: Deploy with Zeploy
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Run
      - name: Ziploy
        uses: code-soup/repo-action@master
        id: ziploy
        with:
          ziploy-id: ${{ secrets.ZIPLOY_ID }}
          ziploy-host: ${{ secrets.ZIPLOY_HOST }}
          ziploy-secret: ${{ secrets.ZIPLOY_SECRET }}
          #ziploy-id: 7
          #ziploy-host: "https://www.ziploy.com/wp-json/ziploy/v1/update"
          #ziploy-secret: "0980a111efbb0e97586d4d26330e3ec54d53eb495081dea9db305a4009857fd4"

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}