name: Ziploy

on:
  workflow_dispatch:
    inputs:
      host:
        description: 'Test scenario tags'
        required: true
        type: string
      secret:
        description: 'Test scenario tags'
        required: true
        type: string

env:
  host: ${{ secrets.MY_HOST }}

jobs:
  my_job:
    runs-on: ubuntu-latest
    name: My secret job
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Run Ziploy
      - name: Pass that env
        uses: code-soup/repo-action@master
        with:
          host: ${{ env.MY_HOST }}
          secret: "my-secret"