name: Deploy with Ziploy

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: false

jobs:
    deploy:
        runs-on: ubuntu-latest
        container: codesoup/pumpkin  # Use your custom Docker image
        steps:
            - uses: actions/checkout@v4

            - name: Install Dependencies (If Not Already Installed)
              run: |
                  yarn install --frozen-lockfile
                  composer install --no-dev --prefer-dist

            - name: Run Ziploy
              run: |
                  ziploy deploy \
                      --host $ZIPLOY_HOST \
                      --id $ZIPLOY_ID \
                      --secret $ZIPLOY_SECRET
              env:
                  ZIPLOY_HOST: ${{ secrets.ZIPLOY_HOST }}
                  ZIPLOY_ID: ${{ secrets.ZIPLOY_ID }}
                  ZIPLOY_SECRET: ${{ secrets.ZIPLOY_SECRET }}

            - name: Start tmate session (debugging)
              uses: mxschmitt/action-tmate@v3
