name: Testing

on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest
    name: My secret job
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Run
      - name: Pass that env
        uses: code-soup/repo-action@master
        with:
          who-to-greet: 'Mona the Octocat'

      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"